### ISSUE TITLE
Installing two different variants.

### ISSUE THREAD

**Issue by b4skyx** [FriendlyNeighborhoodShane/MinMicroG#18]
Been using NoGoolag edition for a while now, but for some reasons I wanted to have what Minimal + Aurora provides. 
Flashing them two in order Minimal -> AuroraServices seems to remove the minimal one. I did a clean flash it.

Is there a way to customize the installer that it doesn't removes but overwrites over the previous installed variants?

**Comment by FriendlyNeighborhoodShane** [comment]
It's possible to modify the installers to coexist. IDK if and what problems will arise because of conflicts, I have never tried that.

It's also possible to selectively install things from larger packs, like trimming down `NoGoolag` to `Minimal` + `Aurora`. This is not actually something I reccomend, because configuration is actually pretty frustrating and error-prone. Not good UX.

I think the much easier solution to your problem here will simply be to use another flashable zip for Aurora Services. Like the one officially provided by whyorean with the releases themselves:
https://gitlab.com/AuroraOSS/AuroraServices/-/releases

**Comment by b4skyx** [comment]
Thanks for the redirection. Flashing the standalone Aurora services sounds like a better approach instead of messing with the installer.
