### ISSUE TITLE
Outdatet Aurora store in release & trouble updating it

### ISSUE THREAD

**Issue by mar565** [FriendlyNeighborhoodShane/MinMicroG#28]
Maybe an issue or maybe just missing clear instructions in the wiki..

First of all. Thank you for the great work! Its great to be able to just flash it and having it working.
I used the NoGoolag bundle. Here I have the following problem. It came with an outdated Aurora store. No big deal, just update it with the working AuroraDroid store; as I thought... Here is the problem.  It shows there is a new version available, but there is no way to install the update. Maybe it being a system app causes the issue?
I solved it by just downloading the newest stable from the official website. It works but I'm loosing some WAF here.

Am I missing something?
Again thank you for the great work.

**Comment by FriendlyNeighborhoodShane** [comment]
Weird, that definitely shouldn't be happening. What android version are you on?

Yeah, the Aurora in the last stable release is outdated. There is a automatic nightly build with the latest: https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.02.20, but I haven't yet released a stable because I wanted to take a stab at an updated patched playstore, but I've been pretty busy since.

IIRC the Aurora folks changed their token dispenser domain, but that shouldn't affect Aurora's own update mechanism, and you did get the update alert.

**Comment by FriendlyNeighborhoodShane** [comment]
Closing because addressed.

**Comment by neitsab** [comment]
Hi, I was just met with the same issue:

* clean install of Arrow 11 Vanilla on Xiaomi Mi 9T (davinci)
* flash Magisk v25.1 + MinMicroG NoGoolag 2.11.1-20220202153503 (Magisk install) from TWRP, all good
* try to use Aurora Store but it hangs forever because it cannot login (anonymous)
* Aurora Droid doesn't automatically offer to update it despite a new version being available (v4.1.1.41 instead of installed 4.0.7.38) on its detail page;  I can download it but it doesn't install, nor does it via the regular File Explorer
* try `adb install -r com.aurora.store.41.apk` via my laptop:
```
Performing Streamed Install
adb: failed to install com.aurora.store.41.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.aurora.store signatures do not match previously installed version; ignoring!]
```
I'm not sure where do I go from there?

> Closing because addressed.

Apparently some issue remains :^p

Thx

**Comment by neitsab** [comment]
Fixed by flashing 
MinMicroG-NoGoolag-UPDATELY-20220513163119.zip  from https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.05.13. A new stable release would be definitely most welcome! :-)

Cheers

**Comment by FriendlyNeighborhoodShane** [comment]
> I can download it but it doesn't install, nor does it via the regular File Explorer
> 
>     * try `adb install -r com.aurora.store.41.apk` via my laptop:
> 
> 
> ```
> Performing Streamed Install
> adb: failed to install com.aurora.store.41.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.aurora.store signatures do not match previously installed version; ignoring!]
> ```

That's because you're using the APK from F-Droid which is signed by F-Droid's own keys, while MinMicroG used the official releases from https://gitlab.com/AuroraOSS signed by their keys.

>     * Aurora Droid doesn't automatically offer to update it despite a new version being available (v4.1.1.41 instead of installed 4.0.7.38) on its detail page

But this part is weird, its own auto-update should have worked regardless.

**Comment by FriendlyNeighborhoodShane** [comment]
A new stable release has been on my to-do for a while, but I just haven't gotten around to hitting a few milestones that i wanted to, including patching an up-to-date playstore for IAPs. It's been a while since I've had time to work on that.

**Comment by neitsab** [comment]
> That's because you're using the APK from F-Droid which is signed by F-Droid's own keys, while MinMicroG used the official releases from https://gitlab.com/AuroraOSS signed by their keys.

Your logic is sound :-D

> But this part is weird, its own auto-update should have worked regardless.

If Aurora Droid only offers the F-Droid built version of the app, then maybe it didn't offer the upgrade despite a newer version being available because it detected their signatures were different? Anticipating the installation wouldn't work it didn't trigger a wasteful download which would have been for nothing. That'd make sense not?

> A new stable release has been on my to-do for a while, but I just haven't gotten around to hitting a few milestones that i wanted to, including patching an up-to-date playstore for IAPs. It's been a while since I've had time to work on that.

No problem, life is what it is and this being freely contributed work by you, I am grateful for whatever your share with the community! I was just saying thinking it would to prevent your receiving more "complaints" by disgruntled users, but as long as this issue doesn't lead to too many reports it is definitely fine to take your time to work on what you want :-)

Cheers

**Comment by FriendlyNeighborhoodShane** [comment]
> > But this part is weird, its own auto-update should have worked regardless.
> 
> If Aurora Droid only offers the F-Droid built version of the app, then maybe it didn't offer the upgrade despite a newer version being available because it detected their signatures were different? Anticipating the installation wouldn't work it didn't trigger a wasteful download which would have been for nothing. That'd make sense no?

AuroraDroid's own update mechanism _should_ (only as far as I can guess) only trigger for the official non-FDroid builds and should only offer their self-signed APKs. Then again, this is only a guess based on how I've seen other apps handle this.

**Comment by TheShanMan** [comment]
I just ran into this problem after installing MinMicroG-NoGoolag. IMO the better approach to avoiding this is only having aurora services (and fdroid privileged extension) installed as privileged apps, and manually installing aurora store from f-droid. That way you don't have to wait for MinMicroG updates if/when this problem happens again. So I uninstalled MinMicroG-NoGoolag and went with MinMicroG-Minimal.

Would be nice if there was a NoGoolag variant with just aurora services though (I'd say the f-droid privileged extension too, but I guess MinMicroG prefers to be aurora-only). But I don't imagine maintaining yet another MinMicroG has much appeal, so at least if someone stumbles across this in the future, they'll see this additional approach which they might find appealing.

Regardless, thank you for MinMicroG.
