### ISSUE TITLE
Instruction clarification for flashing

### ISSUE THREAD

**Issue by herrdeh** [FriendlyNeighborhoodShane/MinMicroG#35]
Could you clarify your flashing instructions, please? - You write "dirty flash" is not recommended. So - can I flash into an existing installation in case I clean cache - or do I need a clean install from scratch?

Thanks a lot in advance, Wolf

**Comment by FriendlyNeighborhoodShane** [comment]
The term "clean flash" as commonly used in the Android modding community, at least as I've heard it, refers to a clean `/data`, not just `/cache`. A "dirty flash" refers to one without having wiped the data partition. (The cache partition in general does not really matter much at all in android functioning.)

So yes, if you have your ROM installed already, you don't have to flash it again, but it is recommended to wipe your data partition.

**Comment by herrdeh** [comment]
Thanks a lot for that hint, and please excuse a further request:
Will a backup of /data by TWRP and then a restore be good enough?

**Comment by FriendlyNeighborhoodShane** [comment]
No, in fact it'd be actively worse :P 
The MinMicroG installer tries to do a few changes to data to work around common dirty-flashing issues (keyword: tries), and this would undo all that.

Moreover, you're sort of misunderstanding the issue here. The state of the data partition during MinMicroG flashing is not the problem here. It's not a MinMicroG issue, it's an Android issue. The state of the data partition during the next boot of Android is the problem here. Android does not like when a bunch of privileged apps have been added to the system partition spontaneously, it is not built to expect something like that happening. It reacts in various broken ways like denying all permissions to all system apps (as disastrous as it sounds).

Most people flash their microG packages (like gapps users) at the start of a fresh ROM installation anyway, so it is hardly a problem. App-level backups and restores of user apps (with e.g. oandbackupx or swift) are fine, as long as those backup apps are smart enough to strip away the old push notif registration data, otherwise those restored apps won't register with microG.

And you can always, I guess, just dirty flash if you really want to see what side-effects you face and if you're okay with them.

**Comment by herrdeh** [comment]
Thank you very much for your reply and your detailed advice.

So it should be save to fully backup my system (I'm using titanium backup), flash and then playback from the backup what's missing, probably without of the contents i have flashed before.

 Correct ?

Am 9. Juli 2022 07:56:21 schrieb FriendlyNeighborhoodShane ***@***.***>:

**Comment by FriendlyNeighborhoodShane** [comment]
I would expect that to work out fine, yes.

**Comment by herrdeh** [comment]
Well. I tried.
* flashing was a breeze
* Titanium Backup did a really bad job in restoring, got stuck with every major app, so I restored them manually, which worked.
* location services worked out of the box

But at the end, MicroG core seems to be no longer available - several apps complain about "play services missing" which did not before (Gboard eg). F-Droid says MicroG core IS installed, with version 1.6.8, IMHO not a microG version. I tried to reinstall the MicroG core apk from F-droid, but that one says "not installed".
When I hit "open" in the MicroG window in F-Droid, "UnifiedNlp Settings" do open instead. 

To my ignorant it looks as if UnifiedNlp sort of pretends to be MicroG. Not so nice...
What can I do?

Cheers,
Wolf

**Comment by FriendlyNeighborhoodShane** [comment]
>     * Titanium Backup did a really bad job in restoring, got stuck with every major app, so I restored them manually, which worked.

Titanium has't been updated in a few years, so it might have incompatibilities with modern android version. I hear a few more-maintained alternatives have popped up since.

> But at the end, MicroG core seems to be no longer available - several apps complain about "play services missing" which did not before (Gboard eg). F-Droid says MicroG core IS installed, with version 1.6.8, IMHO not a microG version. I tried to reinstall the MicroG core apk from F-droid, but that one says "not installed". When I hit "open" in the MicroG window in F-Droid, "UnifiedNlp Settings" do open instead.
> 
> To my ignorant it looks as if UnifiedNlp sort of pretends to be MicroG. Not so nice... What can I do?

Uhm... was the package you flashed `MinMicroG-UNLP-***.zip`, by any chance?

Because yes, that specific package does indeed not install microG (the name is a bit misleading, I'll admit), it installs the standalone UNLP (a subset of microG functionality) and its backends.

**Comment by herrdeh** [comment]
> > But at the end, MicroG core seems to be no longer available -
> > several apps complain about "play services missing" which did not
> > before (Gboard eg). F-Droid says MicroG core IS installed, with
> > version 1.6.8, IMHO not a microG version. I tried to reinstall the
> > MicroG core apk from F-droid, but that one says "not installed".
> > When I hit "open" in the MicroG window in F-Droid, "UnifiedNlp
> > Settings" do open instead.
> >
> > To my ignorant it looks as if UnifiedNlp sort of pretends to be
> > MicroG. Not so nice... What can I do?
> >
>
> Uhm... was the package you flashed MinMicroG-UNLP-***.zip, by any
> chance?
>
I installed MinMicroG-UNLP-2.11.1-20220202153519.zip. Assuming it would
install Nlp and leave the rest untouched - or in a state that I can
restore MicroG core again. but I couldn't.

How can I now? Guess I need to flash MicroG?

Cheers,
Wolf

**Comment by FriendlyNeighborhoodShane** [comment]
> > Uhm... was the package you flashed MinMicroG-UNLP-***.zip, by any chance?

> I installed MinMicroG-UNLP-2.11.1-20220202153519.zip. Assuming it would install Nlp and leave the rest untouched - or in a state that I can restore MicroG core again. but I couldn't.

No, all the MinMicroG packages are mutually exclusive (not like e.g. nanodroid which are a bunch of packages that stack on top of each other) (atleast for now, see https://github.com/FriendlyNeighborhoodShane/MinMicroG/issues/32). The UNLP package installs the standalone UNLP for people that want that, and it conflicts with microG (has the same packagename), which is why you couldn't just restore microG. It was no longer there.

> Guess I need to flash MicroG?

Yes, you need to flash a package that actually installs microG. And again, you don't need the standalone UNLP, because all of its functionality is in microG already.

**Comment by herrdeh** [comment]
Thank you very much for your patience. I guess, this is the essential info:

> MinMicroG packages are mutually exclusive

...and I didn't know that. So flashing [Nogoolag](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/releases/download/2022.02.02/MinMicroG-NoGoolag-2.11.1-20220202153503.zip) should do the trick? That roughly holds the contents I want?

But another question occurs? - How are (microG) updates managed? - Do they still work over F-Droid?

**Comment by FriendlyNeighborhoodShane** [comment]
> So flashing Nogoolag should do the trick? That roughly holds the contents I want?

_That_ really isn't something I would know.

> But another question occurs. - How are (microG) updates managed? - Do they still work over F-Droid?

They do if you have the microG F-Droid repo added. There's no F-Droid builds for microG, only the official ones from microG, and they're the ones that MinMicroG has.
Except that many F-Droid clients, including the official, get confused between the standalone UNLP (which is in F-Droid's own repo) and the actual microG because of the same packagename, and so it might show you the wrong app's name in its GUI.

**Comment by herrdeh** [comment]
I was courageous enough to flash [Nogoolag](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/releases/download/2022.02.02/MinMicroG-NoGoolag-2.11.1-20220202153503.zip) sort of "dirty" into the system - without wiping data again.

MicroG is working since then, location services as well. Aurora shop does not. When trying to log in anonymously, it says ```unable to resolve host "goolag.store": No address associated```. Not crucial - but not nice anyway...

**Comment by FriendlyNeighborhoodShane** [comment]
Neat.

Ah yeah, I guess the Aurora Store present in the last stable release is out of date, and they've changed the anonymous login servers. I've been meaning to make a release for a while, but haven't gotten the time to hit some milsestones.

For now, Aurora Store should just trigger its auto-update mechanism. If it doesn't (they might have used the same servers for the auto-update), you can just get the latest release from here: https://gitlab.com/AuroraOSS/AuroraStore

**Comment by herrdeh** [comment]
Problem was to uninstall Aurora - I had to use TitaniumBckp for that purpose. Well.

So in the end, it was quite a tour d'force. Worst is I lost my signal and threema backups; I expected them to be safe on my SD card, but they were not; a wipe of /data obviously can erase SD card data as well. ):

Thanks a lot for providing these packages anyway. I cannot tell if my use case is a very rare one, if not, users may benefit from more detailled install instructions.

**Comment by FriendlyNeighborhoodShane** [comment]
> So in the end, it was quite a tour d'force. Worst is I lost my signal and threema backups; I expected them to be safe on my SD card, but they were not; a wipe of /data obviously can erase SD card data as well, and neither TitBackp nor NeoBackup is safe on that behalf. ):

Yikes.

> Thanks a lot for providing these packages anyway. I cannot tell if my use case is a very rare one, if not, users may benefit from more detailled install instructions.

That thing about MinMicroG packages being mutually-exclusive has indeed been a point of UX surprise for many users that have been coming over from nanodroid. In fact, I have got an unfinished commit for that, along with the above-mentioned addon thing, on my drive.

Other than that... I honestly don't know what changes could be made in MinMicroG's documentation to avoid the very specific issues that you faced here. Suggestions are welcome.
