### ISSUE TITLE
MinMicroG not working properly when dirty flashing ROM updates

### ISSUE THREAD

**Issue by VesperLlama** [FriendlyNeighborhoodShane/MinMicroG#42]
When I install updates for my ROM, then MinMicroG doesn't work properly. It works fine when I clean flash. I am using the NoGoolag version and some apps like Aurora Services, Gfsproxy, FakeStore disappear after the update. Others like the location backends and GMSCore are still there but apps which require Play Services do not detect it and don't work.

I have tried manually mounting System and System_ext in TWRP but it still doesn't work. Both System and Magisk install show same issue. 

TWRP log -
[recovery.log](https://github.com/FriendlyNeighborhoodShane/MinMicroG/files/9337801/recovery.log)

Device: Redmi Note 10 Pro
Recovery: TWRP 3.6.2_12 (Unofficial but supports decryption) and 3.6.2_11 (Official)
ROM: CrDroid 8 (Android 12.1)
MinMicroG version: 14 August Updately Build same issue with 13 May build and 2 Feb official release.

**Comment by FriendlyNeighborhoodShane** [comment]
That is very weird. Does your ROM come with gapps? My first guess would have been that it does but those disappearing apps are neither the specific ones gapps would be conflicting with, nor does minmicrog find any to debloat on install.

**Comment by eredrolo** [comment]
No, the ROM doesn't come with any GApps (except Android System Intelligence, Device Health Services and Private Compute Services).

I just noticed that you do not recommend dirty flashing MinMicroG in the README. I have been dirty flashing it along with the ROM updates for over an year and I didn't had any problems before, on both A11 and A12. The problem started from last month.

So what is the correct way to handle updates? The recovery now supports A12 decryption and addon.d works for Magisk. So should I just dirty flash the ROM file only and let addon.d do it's work?

**Comment by FriendlyNeighborhoodShane** [comment]
The "dirty flashing" the readme advises against is dirty flashing the MinMicroG zip itself i.e. flashing MinMicroG on top of an installation that has been booted into. For best results, MinMicroG should be flashed while making a fresh rom installation i.e. after wiping /data.

Dirty flashing the ROM's OTA updates on top should not cause any problems. That's how they're meant to be updated. MinMicroG should survie by using addon.d or through magisk.

And... from the logs, to me it seems like addon.d is working fine. Something else is just causing android to 'forget' those apps. This sometimes happens when two apps conflict (like microG and the actual play services, because of their same package name). But I don't know why it could be happening here.

**Comment by VesperLlama** [comment]
I have flashed two updates now and both of them didn't cause any issues. It got fixed by itself 🤔
