### ISSUE TITLE
Use customize.sh instead of writing all things in the update-binary

### ISSUE THREAD

**Issue by ayasa520** [FriendlyNeighborhoodShane/MinMicroG#50]
Since KernelSU and installation via `magisk --install-module` both ignore `update -binary`, I think move the installation logic to  customize.sh would be pretty nice.

This is the part I edited.
https://github.com/ayasa520/MinMicroG/commit/acce3c494cdee47fd822ac9e400ca4b4914d0380

I may have missed something, so just FYI

**Comment by mahmoudk1000** [comment]
I agree. In my opinion, now is the right time for such update.

**Comment by FriendlyNeighborhoodShane** [comment]
Hi,

Thanks for the suggestion, and sorry for the delay in getting back, I wasn't able to give this much attention in the meanwhile.

The thing is, installation using a booted android environment isn't really supported. It being installable through the Magisk app was primarily just a consequence of not explicitly choosing to block installation (like NanoDroid). My recommendation has always been to install it from your recovery, since there you can make changes to /data, like making sure runtime permissions are set even on a dirty flash, without fearing about messing up running state.

But recently, dude to data decryption becoming harder and rarer, doing that or installing as a module from recovery has become unviable. Installation with booted Magisk, kernelSU etc. is something I do want to support and will look into, and in theory it should be fine as long as it follows the principle of mount-on-next-boot (like magisk does). But adjustments need to be made, like doing the data cleanups in an init script next boot.

**Comment by FriendlyNeighborhoodShane** [comment]
@zer0def made the changes necessary for this, here's a CI build:

https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2023.07.31
