### ISSUE TITLE
requirement: Signature Spoofing?

### ISSUE THREAD

**Issue by ansorg** [FriendlyNeighborhoodShane/MinMicroG#6]
hi, I'd like to get clarity on that one: I would need to run a ROM with ```Signature Spoofing``` in order for this installer to work?

**Comment by FriendlyNeighborhoodShane** [comment]
Nope, the installer does not care. It won't even check if the ROM has it.

Signature spoofing _is_ a hard requirement for microG, however. If you want to use microG (nogoolag or standard packages), you _will_ need sigspoof.

To get sigspoof, you can use (on-device) the standalone NanoDroid-patcher or (PC) Haystack or [this](https://www.reddit.com/r/MicroG/comments/fywiix/signature_spoofing_patcher_for_android_q/). I would discourage you from using the SmaliPatcher application, due to the reasons listed in the readme.
